baseURL: /
languageCode: en-us
title: My Digital Garden
theme: digital-garden-theme
copyright: Muhammad Azani Hasibuan ©
params:
  name: Muhammad Azani Hasibuan
  description: AzaNotes
  initials: MAZ
  googleAnalytics: ''
  social:
    - name: Twitter
      link: '#'
      icon: fab fa-twitter
    - name: Github
      link: '#'
      icon: fab fa-github
    - name: Medium
      link: '#'
      icon: fab fa-medium-m
    - name: LinkedIn
      link: '#'
      icon: fab fa-linkedin-in
menu:
  main:
    - name: Digital Garden
      url: /garden/
      weight: 1
    - name: Projects
      url: /projects/
      weight: 2
    - name: Library
      url: /library/
      weight: 3
    - name: About
      url: /about/
      weight: 4
taxonomies:
  garden_tags: garden_tags
  project_tags: project_tags
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
  highlight:
    style: monokailight
